# Generated by Django 3.2.6 on 2021-08-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleModes1',
            new_name='SampleModels',
        ),
    ]
